--- #YAML:1.0
name:               Test-Reporter-Transport-Net-SMTP-Authen
version:            1.02
abstract:           SMTP transport for Test::Reporter 
author:
    - A.G. Grishaev <grian@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Authen::SASL:    0
    CPAN::Reporter:  0
    MIME::Base64:    0
    Net::SMTP:       0
    Net::SMTP::TLS:  0
    perl:            5.008
    Test::Reporter:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
